export default {
  container: {
    backgroundColor: "#0D7E83",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    flexBasis: 220,
    flexShrink: 0,
    minWidth: 1,
    maxWidth: 260,
    zIndex: 200,
  },
  title: {
    color: "#ffffff",
    fontSize: 18,
    lineHeight: "22px",
    whiteSpace: "nowrap",
    fontWeight: 900,
    padding: "0 16px",
    position: "relative",
    zIndex: 50,
    flexBasis: 40,
    flexShrink: 0,
    marginTop: 9,
  },
  channels: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    color: "rgb(182,216,218)",
    position: "relative",
    padding: 0,
    width: "100%",
    height: 500,
    overflow: "hidden",
  },
  channelsTitle: {
    height: 26,
    margin: 0,
    padding: "0 12px 0 15px",
    width: "100%",
    display: "flex",
    alignItems: "center",
    fontSize: 16,
    lineHeight: 1,
    opacity: 1,
  },
}
